name: Build LaTeX document
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Convert to html
        run: |
          sudo apt install -y pandoc
          mkdir ghpages
          pandoc --mathjax --standalone -o ghpages/index.html main.tex --citeproc --bibliography references.bib
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
      - name: Setup deploy folder
        run: |
          mv main.pdf ghpages/main.pdf
      - name: Push PDF to ghpages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ghpages
          single-commit: true
